### ISSUE TITLE
How to make tokens the same?

### ISSUE THREAD

**Issue by Eureka-Maggie** [Betswish/Cross-Lingual-Consistency#1]
Hi! I was confused when reading "We also ensure that, for each edited knowledge, the subject and object entities are the same tokens across all languages." in your case study. I don't quite understand how two different languages can have the same token for the subject and object in a query? And could you please give a more detailed explanation for "Spanish and Vietnamese get consistent predictions with English simply because of the lexical co-occurrence of their subject and object tokens in the evaluated queries." I'm confused about this part.
Thanks！

**Comment by Betswish** [comment]
Hi! Thanks for the question and the following are our thoughts.

For instance, if we insert a piece of counterfactual knowledge 'Steve Jobs is famous for the **_piano_**' (rather than iPhone)
The queries of the four non-English languages should be:

es: **Steve Jobs** es famoso por el --> iPhone/**_piano_**
vi: **Steve Jobs** nổi tiếng với đàn --> iPhone/**_piano_**
hu: **Steve Jobs** híres a --> iPhone/**_zongorájáról_**
el: Ο **Steve Jobs** είναι διάσημος για το --> iPhone/**πιάνο**

Here we can see that the English object 'piano' is the same in Spanish and Vietnamese, but is different tokens in Hungarian and Greek. 

Since ROME and similar editing methods are considered to work at a very lexical level, in the above case, if es and vi change consistently with English while hu/el remain unchanged, people may be concerned that it's simply because the exact token 'piano' didn't show up in Hungarian and Greek, rather than the low CLC.

To avoid such concerns related to the editing methods, we select English sentences where the subject tokens and the object tokens are the same across all languages, as follows:

es (high): **Steve Jobs** trabajó para --> Apple/**_Microsoft_**
vi (high): **Steve Jobs** đã làm việc cho --> Apple/**_Microsoft_**
hu (low): **Steve Jobs** a cégnél dolgozott --> Apple/**_Microsoft_**
el (low): Ο **Steve Jobs** δούλευε για την --> Apple/**_Microsoft_**

**Comment by Eureka-Maggie** [comment]
Wow! Thank you for your quick and patient reply! Your explaination really helps.

**Comment by Betswish** [comment]
Cheers! ;)
